form_types:
  10-K:
    match: '10-?K'
    cutoff_date: '2016-01-01'
    documents:
      - all_of:
          - field: type
            operator: regex
            value: '^EX-21'
      - all_of:
          - field: type
            operator: regex
            value: '^10-K'

  20-F:
    match: '20-?F'
    cutoff_date: '2016-01-01'
    documents:
      - all_of:
          - field: type
            operator: regex
            value: '^EX-8'
      - all_of:
          - field: type
            operator: regex
            value: '^20-F'

  10-Q:
    match: '10-?Q'
    cutoff_date: '2016-01-01'
    documents:
      - all_of:
          - field: type
            operator: regex
            value: '^10-Q'

  8-K:
    match: '8-K'
    cutoff_date: '2016-01-01'
    documents:
      - all_of:
          - field: description
            operator: exact
            value: "Complete submission text file"

  6-K: 
    match: '6-K'
    cutoff_date: '2016-01-01'
    documents:
      - all_of:
          - field: type
            operator: regex
            value: '^6-K'
      - all_of:
          - field: type
            operator: regex
            value: 'EX-(?!101)'

  13F-HR:
    match: '13F-HR'
    cutoff_date: '2016-01-01'
    documents:
      - all_of:
          - field: type
            operator: exact
            value: "INFORMATION TABLE"
          - field: filename
            operator: regex
            value: '(?i).*\.html$'
      - all_of:
          - field: type
            operator: regex
            value: '^13F-HR'
          - field: filename
            operator: regex
            value: '(?i).*\.html$'
